apiVersion: v2
name: unstructured-api
description: A Helm chart for Unstructured-API
icon: https://avatars.githubusercontent.com/u/108372208?s=48&v=4
type: application

version: 0.0.2

appVersion: "0.0.80"
