name: Publish release
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  publish:
    runs-on: unstructured-api-runner

    permissions: write-all

    name: Publish release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish release
        uses: eloquent/github-release-action@v3
        with:
          generateReleaseNotes: "true"
